### ISSUE TITLE
Changing the name

### ISSUE THREAD

**Issue by erlend-sh** [rictic/rust-us#57]
Would you consider a name-change? Rust Us is fine, but it's not very searchable and the relation to Among Us is not clear until actually reading the description. I thought maybe the us in rust-us stood for US(A) when I first found it.

Some suggestions:

- Among Crabs 🦀 
- Among Rustaceans
- Among Rust

**Comment by rictic** [comment]
Yeah!

rust-us is definitely not a great name. The domain name I'm using right now is https://airlock.chat/ so I'll change the repo name to match, and catch people searching for the tech stack (rust, wasm, websockets, etc) in the tags and README.
